using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("Galactic Ads")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.0")]
[assembly: AssemblyTitleAttribute("GalacticAds")]
[assembly: AssemblyProductAttribute("GalacticAds")]
[assembly: AssemblyDescriptionAttribute("GalacticAds is a product of Galactic Ads - https://RhysC@github.com/RhysC/Galacti" +
    "cAds.git.")]
[assembly: AssemblyTrademarkAttribute("GalacticAds - Galactic Ads")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010 Galactic Ads, - Original author or authors")]

